name: Participations

on: [push]

jobs:
  presence:
    name: presence de fichiers pour la participation
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install jq
        run: brew install jq

      - name: Use jq
        run: echo '{"name":"GitHub"}' | jq '.name'
    
      - shell: bash
        run: |
          ##
          ## Evaluating chapter 0.PlanDeCours
          ## 
          echo "Evaluating chapter 0.PlanDeCours Participation"
          cd 0.PlanDeCours
          bash .scripts/run.sh
          cd ..
          ##
          ## Evaluating chapter P.Programmation/1.IDE
          ## 
          echo "Evaluating chapter P.Programmation/1.IDE Participation"
          cd P.Programmation/1.IDE
          bash .scripts/run.sh
          cd ../..
          ##
          ## Evaluating chapter P.Programmation/2.Jupyter
          ##
          echo "Evaluating chapter P.Programmation/2.Jupyter Participation"
          cd P.Programmation/2.Jupyter
          bash .scripts/run.sh
          cd ../..
          ##
          ## Evaluating chapter 2.IO
          ## 
          echo "Evaluating chapter 2.IO Participation"
          cd 2.IO
          bash .scripts/run.sh
          cd ../..
          ##
          ## Evaluating chapter 3.Tris
          ## 
          echo "Evaluating chapter 3.Tris Participation"
          cd 3.Tris
          bash .scripts/run.sh
          cd ../..



      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "VÃ©rification de la participation" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
